# Generated by Django 4.2.7 on 2023-11-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menssage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Telefono')),
                ('address', models.CharField(max_length=256, verbose_name='Dirección')),
                ('details', models.TextField(verbose_name='Detalles')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
