# Generated by Django 4.2.7 on 2023-11-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menssage',
            name='phone',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
