# Generated by Django 4.2.7 on 2023-12-12 01:40

import apps.private.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Logo')),

            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='MobileToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Token de telefono',
                'verbose_name_plural': 'Token de telefonos',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512, verbose_name='Descripción')),
                ('unit', models.CharField(choices=[('0', 'gl'), ('1', 'c/u'), ('2', 'm'), ('3', 'tira')], max_length=1, verbose_name='unidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.provider', verbose_name='Proveedor')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.tag', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Código')),
                ('owner', models.CharField(max_length=128, verbose_name='Cliente')),
                ('materials', models.ManyToManyField(to='private.material', verbose_name='Materiales')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
