# Generated by Django 4.2.7 on 2023-11-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='materiales',
        ),
        migrations.DeleteModel(
            name='DetallePresupuesto',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
    ]
