# Generated by Django 4.2.7 on 2023-11-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024, verbose_name='Descripcion')),
                ('unit', models.CharField(max_length=8, verbose_name='Unidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='media/private'),
        ),
    ]
