# Generated by Django 4.2.7 on 2023-11-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_remove_presupuesto_materiales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('token', models.CharField(max_length=256, verbose_name='Nombre')),
            ],
        ),
    ]
