# Generated by Django 4.2.7 on 2023-11-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_material_alter_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
