# Generated by Django 4.2.7 on 2023-11-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0003_material_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Codigo'),
        ),
    ]
